openapi: 3.0.4
info:
  title: Coordinates Are Sea
  description: >-
    Coordinates are Sea is a simple tool for checking if coordinates are in the
    sea. It returns if the coordinates are in the sea or not.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/coordinatesaresea:
    get:
      summary: Check if Coordinates are in the Sea
      description: Check if the coordinates are in the sea
      operationId: coordinatesaresea
      parameters:
        - name: lat
          in: query
          schema:
            type: number
          required: true
          description: The latitude of the coordinates
          example: 37.7749
        - name: lon
          in: query
          schema:
            type: number
          required: true
          description: The longitude of the coordinates
          example: -122.4194
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  latitude: 37.7749
                  longitude: -122.4194
                  isSea: false
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
